return {
    version = "0.1.0",

    files = {
        "startup.lua",

        "sys/class.lua",
        "sys/config.lua",
        "sys/kernel.lua",
        "sys/screen.lua",
        "sys/theme.lua",
        "sys/filesystem.lua",
        "sys/registry.lua",
        "sys/app_manager.lua",
        "sys/history.lua",
        "sys/autocomplete.lua",
        "sys/logger.lua",
        "sys/terminal.lua",
        "sys/terminal_buffer.lua",
        "sys/terminal_renderer.lua",
        "sys/terminal_input.lua",

        "commands/apps.lua",
        "commands/cat.lua",
        "commands/cd.lua",
        "commands/clear.lua",
        "commands/cls.lua",
        "commands/edit.lua",
        "commands/fetch.lua",
        "commands/help.lua",
        "commands/id.lua",
        "commands/log.lua",
        "commands/ls.lua",
        "commands/mkdir.lua",
        "commands/open.lua",
        "commands/pkg.lua",
        "commands/pwd.lua",
        "commands/reboot.lua",
        "commands/reload.lua",
        "commands/run.lua",
        "commands/theme.lua",

        "lib/help_dialog.lua",

        "apps/about/manifest.lua",
        "apps/about/main.lua",

        "apps/editor/manifest.lua",
        "apps/editor/main.lua",
        "apps/editor/EditorApp.lua",
        "apps/editor/EditorBuffer.lua",
        "apps/editor/EditorView.lua",
        "apps/editor/EditorDialogs.lua",

        "apps/files/manifest.lua",
        "apps/files/main.lua",
        "apps/files/FilesApp.lua",
        "apps/files/FilesData.lua",
        "apps/files/FilesView.lua",

        "apps/launcher/manifest.lua",
        "apps/launcher/main.lua",
        "apps/launcher/LauncherApp.lua",
        "apps/launcher/LauncherData.lua",
        "apps/launcher/LauncherView.lua",

        "apps/logs/manifest.lua",
        "apps/logs/main.lua",
        "apps/logs/LogsApp.lua",
        "apps/logs/LogsData.lua",
        "apps/logs/LogsView.lua",

        "apps/monitor/manifest.lua",
        "apps/monitor/main.lua",
        "apps/monitor/MonitorApp.lua",
        "apps/monitor/MonitorData.lua",
        "apps/monitor/MonitorView.lua",

        "apps/network/manifest.lua",
        "apps/network/main.lua",
        "apps/network/NetworkApp.lua",
        "apps/network/NetworkData.lua",
        "apps/network/NetworkView.lua",
        "apps/network/NetworkDialogs.lua",

        "apps/packages/manifest.lua",
        "apps/packages/main.lua",
        "apps/packages/PackagesApp.lua",
        "apps/packages/PackagesData.lua",
        "apps/packages/PackagesView.lua",
        "apps/packages/PackageTemplate.lua",
        "apps/packages/PackageOperations.lua",

        "apps/settings/manifest.lua",
        "apps/settings/main.lua",
        "apps/settings/SettingsApp.lua",
        "apps/settings/SettingsData.lua",
        "apps/settings/SettingsView.lua",

        "apps/tasks/manifest.lua",
        "apps/tasks/main.lua",
        "apps/tasks/TasksApp.lua",
        "apps/tasks/TasksData.lua",
        "apps/tasks/TasksView.lua"
    }
}